__title__ = "recordclass"
__version__ = "0.24"
__summary__ = "Mutable variant of namedtuple -- recordclass, which support assignments, compact dataclasses and other memory saving variants."
__uri__ = "https://github.com/intellimath/recordclass"
__author__ = "Zaur Shibzukhov"
__email__ = "szport@gmail.com"
__license__ = "MIT"