/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__recordclass__recordobject
#define __PYX_HAVE__recordclass__recordobject

#include "Python.h"
struct SequenceProxyObject;

/* "recordclass/recordobject.pyx":276
 * 
 * @cython.final
 * cdef public class SequenceProxy[object SequenceProxyObject, type SequenceProxyType]:             # <<<<<<<<<<<<<<
 *     cdef object ob "ob"
 *     cdef Py_hash_t hash "hash"
 */
struct SequenceProxyObject {
  PyObject_HEAD
  PyObject *ob;
  Py_hash_t hash;
};

#ifndef __PYX_HAVE_API__recordclass__recordobject

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) SequenceProxyType;

#endif /* !__PYX_HAVE_API__recordclass__recordobject */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initrecordobject(void);
#else
PyMODINIT_FUNC PyInit_recordobject(void);
#endif

#endif /* !__PYX_HAVE__recordclass__recordobject */
